spring:
  datasource:
    url: ${JAVA_ADMIN_STARTER_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/java_admin_starter_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${JAVA_ADMIN_STARTER_DATASOURCE_USERNAME:root}
    password: ${JAVA_ADMIN_STARTER_DATASOURCE_PASSWORD:root}

platform:
  file:
    storage:
      type: ${FILE_STORAGE_TYPE:minio}
      zone-id: ${FILE_STORAGE_ZONE_ID:Asia/Shanghai}

logging:
  level:
    root: WARN
    com.example.admin: INFO
