spring:
  datasource:
    url: ${JAVA_ADMIN_STARTER_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3300/java_admin_starter_iam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${JAVA_ADMIN_STARTER_DATASOURCE_USERNAME:root}
    password: ${JAVA_ADMIN_STARTER_DATASOURCE_PASSWORD:root}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1

platform:
  iam:
    jwt-secret: ${IAM_JWT_SECRET}
  file:
    storage:
      type: ${FILE_STORAGE_TYPE:local}
      zone-id: ${FILE_STORAGE_ZONE_ID:Asia/Shanghai}
      local:
        root-dir: ${user.home}/.java-admin-starter/uploads
        base-url: /local-files

logging:
  level:
    root: INFO
    com.example.admin: DEBUG
    com.github.xiaoymin.knife4j: DEBUG
    org.springdoc: DEBUG
