create table sys_export_record_global (
  id bigint primary key,
  export_biz_code varchar(64) not null,
  export_biz_name varchar(128) not null,
  file_name varchar(256) not null,
  file_type varchar(32) not null,
  content_type varchar(128) null,
  file_size bigint null,
  object_key varchar(256) null,
  storage_type varchar(32) null,
  status tinyint not null,
  finished_time datetime null,
  expire_time datetime not null,
  deleted_time datetime null,
  delete_reason tinyint null,
  fail_code varchar(64) null,
  fail_message varchar(255) null,
  query_snapshot_json longtext not null,
  query_snapshot_summary varchar(512) not null,
  download_count int not null default 0,
  last_download_time datetime null,
  last_download_by bigint null,
  expire_seconds int not null,
  create_time datetime not null default current_timestamp,
  update_time datetime not null default current_timestamp,
  create_by bigint null,
  update_by bigint null,
  deleted bigint not null default 0 comment '逻辑删除：0未删除，1已删除',
  key idx_sys_export_record_global_creator_status_time (create_by, status, create_time),
  key idx_sys_export_record_global_status_expire_time (status, expire_time),
  key idx_sys_export_record_global_biz_code_time (export_biz_code, create_time)
);
